feat: attempt to addi codecov to project

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -44,3 +44,6 @@ jobs:
     - name: Run Tests
       run: |
         python manage.py test
+    - name: Uploading codecov reports
+      run: |
+        bash <(curl -s https://codecov.io/bash) -v || echo 'Codecov failed to upload'
