🧪 test: codecov uploading
* feat: attempt to addi codecov to project

* 🧪 test: coverage.py added

* test: Coverage.py

* Update django.yml

* feat: attempt to addi codecov to project

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -47,3 +47,6 @@ jobs:
     - name: Coverage
       run: |
         coverage run --source='.' manage.py test app
+    - name: Uploading codecov reports
+      run: |
+        bash <(curl -s https://codecov.io/bash) -v || echo 'Codecov failed to upload'
